### ISSUE TITLE
Customizable icon for selected item?

### ISSUE THREAD

**Issue by nartc** [redplane/ng2-multi-selector#1]
Like title said, would there be a way to customize the icon on selected item? Apparently, there are use-cases where different icons or no icon at all might be more applicable.

**Comment by redplane** [comment]
Version `3.0.5` has been released.
Please use `item-template` option to create item template. You can refer to this [Online Demo](https://ngx-multi-selector.netlify.com/advanced-demo/custom-item-template).

I'll close this issue. Please feel free to re-open if it doesn't meet your requirement.
